# Generated by Django 4.2.1 on 2023-05-06 16:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail_retail.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_retail.core.models.BaseShopConfig, 'wagtailcore.page', models.Model),
        ),
    ]
