# Generated by Django 4.2.1 on 2023-05-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productpage_list_description_productpage_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpage',
            old_name='list_description',
            new_name='summary',
        ),
    ]
