# Generated by Django 4.2.1 on 2023-05-07 16:20

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_list_description_productpage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
